development:
  adapter: mysql2
  database: floatingbill_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: floatingbill_test
  username: root
  password:
  socket: /tmp/mysql.sock